### PR TITLE
:new: :memo: examples: Initialize reading list (closes #10)

### LINKED ISSUE #10: To add to the repo/inventory
https://wiki.documentfoundation.org/Design/Principles

### PR DESCRIPTION
**Pull request by jwflory**
This commit creates a reading list page in the _Case Studies & Examples_ page, as discussed in issue #10. This can be a catch-all resource for links, resources, articles, and other content that we don't necessarily wish to repeat, but wish to provide as a reference for others who are discovering our work.

The reading list is initialized with the LibreOffice UX Principles, as shared by @Erioldoesdesign.

Closes #10.

Locally-rendered screenshot of the new Reading List page in the Case Studies & Examples category. The LibreOffice UX Principles page is highlighted.

### CODE REVIEW

**Comment by RichardLitt** [comment]
How do I host this site locally, or how can I check a test deployment?

**Comment by jwflory** [comment]
> **_@RichardLitt wrote…_**
> How do I host this site locally, or how can I check a test deployment?

That is a great question, and worthy of new documentation in the `README.md`. I'll follow up with a new Pull Request.

**Comment by RichardLitt** [comment]
Thanks. I can't approve of this until I see how you got what you rendered! :D

**Comment by jwflory** [comment]
To that end, I added instructions for setting up a developer environment in PR #13.

**Comment by RichardLitt** [comment]
Is there a reason we need a new page? Can't this be in Case Studies?

**Comment by jwflory** [comment]
Oh. I forgot we had that page. The Case Studies page was the one I imported from the UNICEF Open Source Inventory. It could just as easily fit there, I think.

**Comment by RichardLitt** [comment]
I would suggest moving it there, then. :)

**Comment by jwflory** [comment]
I fixed up my original commit and pushed a new commit, 43e467aaa6bca52b4c6bd56f3f270a5373cc57e2, that adds the Document Founation principles to the Case Studies page.

**Comment by RichardLitt** [comment]
Thanks @jwflory

**Pull request merged**
