### PR TITLE
I added the definitions of each area

### PR DESCRIPTION
**Pull request by Erioldoesdesign**
I'm not sure how this works because I've not worked with this template before? is this in Hugo? I'm not sure If I've built it right or anything :/

### CODE REVIEW

**Comment by Erioldoesdesign** [comment]
Updated my branch/PR with the suggestions from the form.

**Comment by Erioldoesdesign** [comment]
I added @jwflory and @RichardLitt as reviewers because i am convinced i did not do this correctly 😅

**Comment by jwflory** [comment]
The CI pipeline is not verbose about what is wrong. I cloned this branch locally and ran the checker tool. The build is failing for this reason:

```html
- ./public/designers/tools/index.html
  *  internally linking to Penpot.app, which does not exist (line 314)
     <a href="Penpot.app"><strong>Penpot.app</strong></a>
- ./public/examples/case-studies/index.html
  *  internally linking to Simple.org, which does not exist (line 314)
     <a href="Simple.org"><strong>Simple.org</strong></a>

HTML-Proofer found 2 failures!
```

Changing the following two lines to use a URL (e.g. `[**Simple.org**](https://simple.org)`) should fix this:

https://github.com/sustainers/design/pull/6/commits/e23256de0d5e0d6dd747c1f49fe628b0d318c59b#diff-a7490d066ac8efb1f7d583e799e70c03adfab580c70944e630ddbefb0661d0b4R11

https://github.com/sustainers/design/pull/6/commits/e23256de0d5e0d6dd747c1f49fe628b0d318c59b#diff-dc70063e77eae8cbfb37e5ac5afc1c6d8d0dcf148a42d7aa8d69cb32139c368cR11

**Review by RichardLitt — COMMENTED** [review]
Approved. I made some slight wording changes here and there. :)

**Comment by jwflory** [comment]
Teamwork makes the dream work 🚀 😎

**Comment by RichardLitt** [comment]
I did it all. :) Thanks @jwflory for pointing out errors!

**Pull request merged**
